agora/urls.py
from django.urls import path
from . import views

app_name="agora"

urlpatterns = [
    path('room/', views.index, name='agora-index'),
    path('pusher/auth/', views.pusher_auth, name='agora-pusher-auth'),
    path('token/', views.generate_agora_token, name='agora-token'),
    path('call-user/', views.call_user, name='agora-call-user'),
]

core/urls.py
from django.urls import path
from .views import PanelView, delete_account, home
from django.conf.urls.static import static
from django.conf import settings

app_name = 'core'

urlpatterns = [
    path('', home, name="home"),
    path('panel/', PanelView.as_view(), name="panel"),
    path('delete/', delete_account, name="delete_account" )
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

medau/urls.py

from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('agora.urls', namespace='agora')),
    path('', include('friends.urls', namespace='friends')),
]

templates/base_panel.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
		<meta charset="utf-8">
		<title>Medau - online doctor's call</title>
		<meta name="description" content="#">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap core CSS -->
		<link href="{% static 'css/lib/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
		<!-- Swipe core CSS -->
		<link href="{% static 'css/swipe.min.css' %}" type="text/css" rel="stylesheet">
		<!-- Favicon -->
		<link href="{% static 'img/favicon.png' %}" type="image/png" rel="icon">
		<!-- Video chat stream CSS -->
		<link href="{% static 'css/stream.css' %}" type="text/css" rel="stylesheet">
		<!-- Fontawsome Icons -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

	</head>

<body>
		<main>

			<div class="layout">
					{% if user.is_authenticated %}
						{% include "navbar_panel.html" %}

						{% include "sitebar_panel.html" %}

					{% endif %}
					{% block content %}

					{% endblock content %}


            </div>
</body>

<!-- Bootstrap/Swipe core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-slim.min.js' %}"><\/script>')</script>
<script src="{% static 'js/vendor/popper.min.js' %}"></script>
<script src="{% static 'js/swipe.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/AgoraRTC_N-4.9.0.js' %}"></script>
<script type="text/javascript" src="{% static 'js/streams.js' %}"></script>
<script type="text/javascript" src="{% static 'js/friends.js' %}"></script>
<script>
			function scrollToBottom(el) { el.scrollTop = el.scrollHeight; }
			scrollToBottom(document.getElementById('content'));
</script>

templates/empty_panel.html
{% extends 'base_panel.html' %}

{% load static %}

{% block content %}

<div class="main">
	<div class="tab-content" id="nav-tabContent">
        <div class="chat" id="chat">
                        <div class="top">
                            <div class="container">
                                <div class="col-md-12">
                                    <div class="inside">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="content empty">
                            <div class="container">
                                <div class="col-md-12">
                                    <div class="no-messages">
                                        <i class="material-icons md-48">forum</i>
                                        <p>Seems people are shy to start the chat. Break the ice, send the first message.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
        </div>
    </div>
</div>
{% endblock %}

templates/home.html
{% load static %}

<p>Here will be a landing page soon...</p>


<a class="btn" href="{% url 'account_login' %}">KLIK</a>



templates/index.html
{% extends 'base_panel.html' %}

{% load static %}

{% block content %}
<div class="main">
	<div class="tab-content" id="nav-tabContent">

		<!-- Start of Empty -->
		<div class="babble tab-pane fade" id="list-empty" role="tabpanel" aria-labelledby="list-empty-list">
			<!-- Start of Chat -->
			<div class="chat" id="chat">
				<div class="top">
					<div class="container">
						<div class="col-md-12">
							<div class="inside">
							</div>
						</div>
					</div>
				</div>
				<div class="content empty">
					<div class="container">
						<div class="col-md-12">
							<div class="no-messages">
								<i class="material-icons md-48">forum</i>
								<p>Seems people are shy to start the chat. Break the ice send the first message.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- End of Chat -->
		</div>
		<!-- End of Empty -->


		<!-- Start of Babble -->
		<div class="babble tab-pane fade active show" id="list-chat" role="tabpanel" aria-labelledby="list-chat-list">

			<!-- Start of Chat -->
			<div class="chat" id="chat1">
				<div class="top">
					<div class="container">
						<div class="col-md-12">
							<div class="inside">
								<a href="#"><img class="avatar-md" src="{% static 'img/avatars/avatar-female-5.jpg' %}" data-toggle="tooltip" data-placement="top" title="Keith" alt="avatar"></a>
								<div class="status">
									<i class="material-icons online">fiber_manual_record</i>
								</div>
								<div class="data">
									<h5><a href="#">Keith Morris</a></h5>
									<span>Active now</span>
								</div>
								<button class="btn connect d-md-block d-none" id="join-btn" name="1"><i class="material-icons md-36">videocam</i></button>
								<a type="submit" class="btn" id="join-btn" name="1"><i class="material-icons md-30">videocam</i></a>
								<button class="btn d-md-block d-none"><i class="material-icons md-30">info</i></button>
								<div class="dropdown">
									<button class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="material-icons md-30">more_vert</i></button>
									<div class="dropdown-menu dropdown-menu-right">
										<button class="dropdown-item connect" name="1"><i class="material-icons">videocam</i>Video Call</button>
										<hr>
										<button class="dropdown-item"><i class="material-icons">clear</i>Clear History</button>
										<button class="dropdown-item"><i class="material-icons">block</i>Block Contact</button>
										<button class="dropdown-item"><i class="material-icons">delete</i>Delete Contact</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="content" id="content">
					<div class="container">
						<div class="col-md-12">
							<div class="date">
								<hr>
								<span>Yesterday</span>
								<hr>
							</div>
							<div class="message">
								<img class="avatar-md" src="{% static 'img/avatars/avatar-female-5.jpg' %}" data-toggle="tooltip" data-placement="top" title="Keith" alt="avatar">
								<div class="text-main">
									<div class="text-group">
										<div class="text">
											<p>We've got some killer ideas kicking about already.</p>
										</div>
									</div>
									<span>09:46 AM</span>
								</div>
							</div>
							<div class="message me">
								<div class="text-main">
									<div class="text-group me">
										<div class="text me">
											<p>Can't wait! How are we coming along with the client?</p>
										</div>
									</div>
									<span>11:32 AM</span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="container">
					<div class="col-md-12">
						<div class="bottom">
							<form class="position-relative w-100">
								<textarea class="form-control" placeholder="Start typing for reply..." rows="1"></textarea>
								<button class="btn emoticons"><i class="material-icons">insert_emoticon</i></button>
								<button type="submit" class="btn send"><i class="material-icons">send</i></button>
							</form>
							<label>
								<input type="file">
								<span class="btn attach d-sm-block d-none"><i class="material-icons">attach_file</i></span>
							</label>
						</div>
					</div>
				</div>
			</div>
			<!-- End of Chat -->

			<!-- Start of Videocall -->
			<div class="call" id="call1">
				<div class="content">
					<div class="container">
						<div class="col-md-12">
							<div class="inside">
								<div class="panel">
									<div class="participant">

											<div id="video-streams">

											</div>

									</div>
									<div class="options">
										<button class="btn option"><i class="material-icons md-30">mic</i></button>
										<button class="btn option"><i class="material-icons md-30">videocam</i></button>
										<button class="btn option call-end"><i class="material-icons md-30">call_end</i></button>
										<button class="btn option"><i class="material-icons md-30">person_add</i></button>
										<button class="btn option"><i class="material-icons md-30">volume_up</i></button>
									</div>
									<button class="btn back" name="1"><i class="material-icons md-24">chat</i></button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- End of Videocall -->

		</div>
		<!-- End of Babble -->

		<!-- Start of Babble -->
		<div class="babble tab-pane fade" id="list-empty" role="tabpanel" aria-labelledby="list-empty-list">
			<!-- Start of Chat -->
			<div class="chat" id="chat2">
				<div class="top">
					<div class="container">
						<div class="col-md-12">
							<div class="inside">
							</div>
						</div>
					</div>
				</div>
				<div class="content empty">
					<div class="container">
						<div class="col-md-12">
							<div class="no-messages">
								<i class="material-icons md-48">forum</i>
								<p>Seems people are shy to start the chat. Break the ice send the first message.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- End of Chat -->
		</div>
		<!-- End of Babble -->

		<!-- Start of Babble -->
		<div class="babble tab-pane fade" id="list-request" role="tabpanel" aria-labelledby="list-request-list">
			<!-- Start of Chat -->
			<div class="chat" id="chat3">
				<div class="top">
					<div class="container">
						<div class="col-md-12">
							<div class="inside">
								<a href="#"><img class="avatar-md" src="{% static 'img/avatars/avatar-female-6.jpg' %}" data-toggle="tooltip" data-placement="top" title="Louis" alt="avatar"></a>
								<div class="status">
									<i class="material-icons offline">fiber_manual_record</i>
								</div>
								<div class="data">
									<h5><a href="#">Louis Martinez</a></h5>
									<span>Inactive</span>
								</div>
								<button class="btn disabled d-md-block d-none" disabled><i class="material-icons md-30">phone_in_talk</i></button>
								<button class="btn disabled d-md-block d-none" disabled><i class="material-icons md-36">videocam</i></button>
								<button class="btn d-md-block disabled d-none" disabled><i class="material-icons md-30">info</i></button>
								<div class="dropdown">
									<button class="btn disabled" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" disabled><i class="material-icons md-30">more_vert</i></button>
									<div class="dropdown-menu dropdown-menu-right">
										<button class="dropdown-item"><i class="material-icons">phone_in_talk</i>Voice Call</button>
										<button class="dropdown-item"><i class="material-icons">videocam</i>Video Call</button>
										<hr>
										<button class="dropdown-item"><i class="material-icons">clear</i>Clear History</button>
										<button class="dropdown-item"><i class="material-icons">block</i>Block Contact</button>
										<button class="dropdown-item"><i class="material-icons">delete</i>Delete Contact</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="content empty">
					<div class="container">
						<div class="col-md-12">
							<div class="no-messages request">
								<a href="#"><img class="avatar-xl" src="{% static 'img/avatars/avatar-female-6.jpg' %}" data-toggle="tooltip" data-placement="top" title="Louis" alt="avatar"></a>
								<h5>Louis Martinez would like to add you as a contact. <span>Hi Keith, I'd like to add you as a contact.</span></h5>
								<div class="options">
									<button class="btn button"><i class="material-icons">check</i></button>
									<button class="btn button"><i class="material-icons">close</i></button>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="container">
					<div class="col-md-12">
						<div class="bottom">
							<form class="position-relative w-100">
								<textarea class="form-control" placeholder="Messaging unavailable" rows="1" disabled></textarea>
								<button class="btn emoticons disabled" disabled><i class="material-icons">insert_emoticon</i></button>
								<button class="btn send disabled" disabled><i class="material-icons">send</i></button>
							</form>
							<label>
								<input type="file" disabled>
								<span class="btn attach disabled d-sm-block d-none"><i class="material-icons">attach_file</i></span>
							</label>
						</div>
					</div>
				</div>
			</div>
			<!-- End of Chat -->
		</div>
		<!-- End of Babble -->
	</div>
</div>





{% endblock content %}

templates/messages.html
{% for message in messages %}
  <div id="message_container" class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}


templates/navbar_panel.html
{% load static %}

<!-- Start of Navigation -->
<div class="navigation">
	<div class="container">
		<div class="inside">
			<div class="nav nav-tab menu">
				{{ user }}
				<button class="btn"><img class="avatar-xl" src="{{ user.account.account_image.url }}" alt="avatar"></button>
				<a href="#members" data-toggle="tab"><i class="material-icons">account_circle</i></a>
				<a href="#discussions" data-toggle="tab" class="active"><i class="material-icons active">chat_bubble_outline</i></a>
				<a href="#notifications" data-toggle="tab" class="f-grow1"><i class="material-icons">notifications_none</i></a>
				<button class="btn mode"><i class="material-icons">brightness_2</i></button>
				<a href="#settings" data-toggle="tab"><i class="material-icons">settings</i></a>
				<a class="btn power" type="sumbit" href="{% url 'account_logout' %}"><i class="material-icons">power_settings_new</i></a>
			</div>
		</div>
	</div>
</div>
<!-- End of Navigation -->


templates/room.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="Build A Scalable Video Chat Application With Agora"
    />
    <meta
      name="keywords"
      content="Video Call, Agora, Django, Real Time Engagement"
    />
    <meta name="author" content="Kofi Obrasi Ocran" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'agora/index.css' %}"
    />
    <script src="https://cdn.agora.io/sdk/release/AgoraRTCSDK-3.3.1.js"></script>
    <title>Agora Video Chat Django</title>
  </head>
  <body>
    <main id="app">
      <main>
        <div class="container">
          <div class="row">
            <div class="col-12 text-center">
              <img
                src="{% static 'agora/agora-logo.png' %}"
                alt="Agora Logo"
                class="block img-fuild"
              />
            </div>
          </div>
        </div>
        <div class="container my-5">
          <div class="row">
            <div class="col">
              <div class="btn-group" role="group">
                {% for singleUser in allUsers%}
                <button
                  type="button"
                  class="btn btn-primary mr-2"

                  @click="placeCall('{{singleUser.id}}','{{singleUser}}')"
                >
                  Call {{ singleUser }}
                  <span class="badge badge-light"
                    >${ getUserOnlineStatus({{singleUser.id}})}</span
                  >
                </button>

                {% endfor %}
              </div>
            </div>
          </div>

          <!-- Incoming Call  -->
          <div class="row my-5" v-if="incomingCall">
            <div class="col-12">
              <p>Incoming Call From <strong>${ incomingCaller }</strong></p>
              <div class="btn-group" role="group">
                <button
                  type="button"
                  class="btn btn-danger"
                  data-dismiss="modal"
                  @click="declineCall"
                >
                  Decline
                </button>
                <button
                  type="button"
                  class="btn btn-success ml-5"
                  @click="acceptCall"
                >
                  Accept
                </button>
              </div>
            </div>
          </div>
          <!-- End of Incoming Call  -->
        </div>

        <section id="video-container" v-if="callPlaced">
          <div id="local-video"></div>
          <div id="remote-video"></div>

          <div class="action-btns">
            <button
              type="button"
              class="btn btn-info"
              @click="handleAudioToggle"
            >
              ${ mutedAudio ? "Unmute" : "Mute" }
            </button>
            <button
              type="button"
              class="btn btn-primary mx-4"
              @click="handleVideoToggle"
            >
              ${ mutedVideo ? "ShowVideo" : "HideVideo" }
            </button>
            <button type="button" class="btn btn-danger" @click="endCall">
              EndCall
            </button>
          </div>

        </section>
      </main>
    </main>
    <!-- Add Scripts -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pusher/7.0.3/pusher.min.js"></script>
    <script>
      window.pusher = new Pusher("25b35b9178f2093c4126", {
        cluster: 'APP_CLUSTER',
        authEndpoint: "{% url 'agora:agora-pusher-auth' %}",
        auth: {
          headers: {
            "X-CSRFToken": "{{ csrf_token }}",
          },
        },
      });

      const AUTH_USER = "{{user}}"
      const AUTH_USER_ID =  "{{request.user.id}}"
      const CSRF_TOKEN = "{{ csrf_token }}"
    </script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js""
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="{% static 'js/streams1.js' %}"></script>
  </body>
</html>

templates/sign-in.html
{% extends 'base_panel.html' %}
{% load i18n %}
{% load account socialaccount %}
{% load static %}

{% block content %}

<div class="layout">
	<!-- Start of Sign In -->
	<div class="main order-md-1">
		<div class="start">
			<div class="container">
				<div class="col-md-12">
					<div class="content">
						<h1>Sign in to Swipe</h1>
						<div class="third-party">
							<button class="btn item bg-blue">
								<i class="material-icons">pages</i>
							</button>
							<button class="btn item bg-teal">
								<i class="material-icons">party_mode</i>
							</button>
							<button class="btn item bg-purple">
								<i class="material-icons">whatshot</i>
							</button>
						</div>
						<p>or use your account:</p>


<!--						<form>-->
<!--							<div class="form-group">-->
<!--								<input type="email" id="inputEmail" class="form-control" placeholder="Email Address" required>-->
<!--								<button class="btn icon"><i class="material-icons">mail_outline</i></button>-->
<!--							</div>-->
<!--							<div class="form-group">-->
<!--								<input type="password" id="inputPassword" class="form-control" placeholder="Password" required>-->
<!--								<button class="btn icon"><i class="material-icons">lock_outline</i></button>-->
<!--							</div>-->
<!--							<button type="submit" class="btn button" formaction="index-2.html">Sign In</button>-->
<!--							<div class="callout">-->
<!--								<span>Don't have account? <a href="sign-up.html">Create Account</a></span>-->
<!--							</div>-->
<!--						</form>-->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End of Sign In -->
	<!-- Start of Sidebar -->
	<div class="aside order-md-2">
		<div class="container">
			<div class="col-md-12">
				<div class="preference">
					<h2>Hello, Friend!</h2>
					<p>Enter your personal details and start your journey with Swipe today.</p>
					<a href="{% url 'core:signup_view' %}" class="btn button">Sign Up</a>
				</div>
			</div>
		</div>
	</div>
	<!-- End of Sidebar -->
</div> <!-- Layout -->

{% endblock %}

templates/sign-up.html
{% extends 'base_panel.html' %}

{% load static %}

{% block content %}

	<body class="start">
		<main>
			<div class="layout">
				<!-- Start of Sign Up -->
				<div class="main order-md-2">
					<div class="start">
						<div class="container">
							<div class="col-md-12">
								<div class="content">
									<h1>Create Account</h1>
									<div class="third-party">
										<button class="btn item bg-blue">
											<i class="material-icons">pages</i>
										</button>
										<button class="btn item bg-teal">
											<i class="material-icons">party_mode</i>
										</button>
										<button class="btn item bg-purple">
											<i class="material-icons">whatshot</i>
										</button>
									</div>
									<p>or use your email for registration:</p>
									<form class="signup">
										<div class="form-parent">
											<div class="form-group">
												<input type="text" id="inputName" class="form-control" placeholder="Username" required>
												<button class="btn icon"><i class="material-icons">person_outline</i></button>
											</div>
											<div class="form-group">
												<input type="email" id="inputEmail" class="form-control" placeholder="Email Address" required>
												<button class="btn icon"><i class="material-icons">mail_outline</i></button>
											</div>
										</div>
										<div class="form-group">
											<input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
											<button class="btn icon"><i class="material-icons">lock_outline</i></button>
										</div>
										<button type="submit" class="btn button" formaction="index-2.html">Sign Up</button>
										<div class="callout">
											<span>Already a member? <a href="sign-in.html">Sign In</a></span>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- End of Sign Up -->
				<!-- Start of Sidebar -->
				<div class="aside order-md-1">
					<div class="container">
						<div class="col-md-12">
							<div class="preference">
								<h2>Welcome Back!</h2>
								<p>To keep connected with your friends please login with your personal info.</p>
								<a href="{% url 'account_login' %}" class="btn button">Sign In</a>
							</div>
						</div>
					</div>
				</div>
				<!-- End of Sidebar -->
			</div> <!-- Layout -->
		</main>
<!--		&lt;!&ndash; Bootstrap core JavaScript-->
<!--		================================================== &ndash;&gt;-->
<!--		&lt;!&ndash; Placed at the end of the document so the pages load faster &ndash;&gt;-->
<!--		<script src="dist/js/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<!--		<script>window.jQuery || document.write('<script src="dist/js/vendor/jquery-slim.min.js"><\/script>')</script>-->
<!--		<script src="dist/js/vendor/popper.min.js"></script>-->
<!--		<script src="dist/js/bootstrap.min.js"></script>-->
	</body>

{% endblock %}